from django.contrib import admin
from project.models import *

admin.site.register(VideoUpload)
admin.site.register(VideoNote)
admin.site.register(Agency)
admin.site.register(Profile)
admin.site.register(Message)
admin.site.register(Star)
admin.site.register(PageVisit)
admin.site.register(Error)
admin.site.register(ClinicalNote)
admin.site.register(Level)
admin.site.register(Section)
admin.site.register(Page)
admin.site.register(Edge)
admin.site.register(Permission)
admin.site.register(Media)
admin.site.register(Tip)
admin.site.register(CustomPage)
admin.site.register(Question)
admin.site.register(Choice)
admin.site.register(Response)
admin.site.register(HVPage)
admin.site.register(HVEdge)
admin.site.register(HVPermission)
admin.site.register(HVQuestion)
admin.site.register(HVChoice)
admin.site.register(HVResponse)
admin.site.register(HVTip)
admin.site.register(HVCustomPage)
admin.site.register(HVLevel)
admin.site.register(HVSection)